//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class documento
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public byte[] Archivo { get; set; }
        public Nullable<int> idProspecto { get; set; }
    
        public virtual tablaProspecto tablaProspecto { get; set; }
    }
}
